// src/vue/App.vue
<template>

      <div>
        <h3>Vue Click Count: {{ count }}</h3>

        <button @click="increment">Increment Count</button>
      </div>
</template>

<script>
export default {
  data() {
    return {
      count: window.store.count,
    }
  },
  methods: {
    increment() {
      window.store.increment()
    },
  },
  mounted() {
    window.store.subscribe(() => {
      this.count = window.store.count
    })
  },
}
</script>

// src/react/App.tsx
import React, {useEffect, useState} from 'react'

const App = () => {
  const [count, setCount] = useState(window.store.count)

  useEffect(() => {
    window.store.subscribe(() => {
      setCount(window.store.count)
    })
  }, [])

  return (
    <div>
      <h2>React Clicks Count: {count}</h2>
    </div>
  )
}

export default App
